### ISSUE TITLE
How to install it?

### ISSUE THREAD

**Issue by MasterGroosha** [jordanrinke/ipsets-persistent#3]
Sorry for such question, however I'm not very familiar with systemd in Ubuntu 16.04 and installing your service using manual didn't seem to work.
Steps I performed:

1) Downloaded `iptables-persistent` script and placed it to `/etc/init.d`
2) Created folder `/etc/iptables`
3) Created file `/etc/systemd/system/iptables-persistent.service` with the following content:

```
[Unit]
Description=Make iptables/ipset persistent

[Service]
Type=simple
ExecStart=/etc/init.d/iptables-persistent start
Restart=on-failure
```

Then started it via `sudo service iptables-persistent start` and saved my current config via `sudo service iptables-persistent save`. Current config was successfully written to `/etc/iptables`

However after reboot, both `ipset -L` and `iptables -L` return empty values.
From the `sudo service iptables-persistent status` I see:

```
● iptables-persistent.service - Make iptables/ipset persistent
   Loaded: loaded (/etc/systemd/system/iptables-persistent.service; static; vendor preset: enabled)
   Active: inactive (dead)

oct 05 11:14:25 router iptables-persistent[1093]:  *  IPv4...
oct 05 11:14:25 router iptables-persistent[1093]:  *  IPv6...
oct 05 11:14:25 router iptables-persistent[1093]:    ...fail!
oct 05 11:14:25 router systemd[1]: iptables-persistent.service: Main process exited, code=exited, status=1/FAILURE
oct 05 11:14:25 router systemd[1]: iptables-persistent.service: Unit entered failed state.
oct 05 11:14:25 router systemd[1]: iptables-persistent.service: Failed with result 'exit-code'.
oct 05 11:14:25 router systemd[1]: iptables-persistent.service: Service hold-off time over, scheduling restart.
oct 05 11:14:25 router systemd[1]: Stopped Make iptables/ipset persistent.
oct 05 11:14:25 router systemd[1]: iptables-persistent.service: Start request repeated too quickly.
oct 05 11:14:25 router systemd[1]: Failed to start Make iptables/ipset persistent.
```

Could you please explain what I'm doing wrong? 

P.S. In `sudo service iptables-persistent status` I see a line: `*  Skipping IPset (no rules to load)`, though `rules.ipset` file in `/etc/iptables` has the necessary strings.

**Comment by jordanrinke** [comment]
This is an addon for iptables-persistent. So what you need to do in this case is remove the service you manually created and then install iptables-persistent (or netfilter-persistent on newer repos/builds) then once that is installed you copy this file into '/usr/share/netfilter-persistent/plugins.d/'

So, this adds ipset support to the iptables-persistent (or netfilter-persistent) package found in most distros. If you have any more questions feel free to ask, sorry for the slow response I must have missed the notification for a comment on this repo.

**Comment by notDavid** [comment]
I was also confused, since there's also a file `iptables-persistent` in this repo, so i thought this file had modifications that are needed as well...

So in Debian/Ubuntu, if the package `iptables-persistent` is installed, only `10-ipset` needs to be placed into `/usr/share/netfilter-persistent/plugins.d/`. Might be useful noting that in the readme!

**Comment by jordanrinke** [comment]
Correct, I will update the readme - that services file was from before netfilter switched to implementing plugins so it is effectively only there for older/legacy systems. I will update the readme to reflect this.
