### ISSUE TITLE
Need clear instructions for different systems

### ISSUE THREAD

**Issue by johnramsden** [jordanrinke/ipsets-persistent#5]
I would like to use this plugin on Ubuntu 14.04. What is unclear to me is whether or not I can use this with iptables-persistent, whether netfilter-persistent is required, and how exactly to use the plugin. 

Can this be used on systems with init rather than systemd? If so how should I install it?

**Comment by jordanrinke** [comment]
I am sure you have solved this already, but for clarity, you can use this on init.d based system. There are two things in the same repo, the original iptables-persistent script fixes, and the netfilter one. On an older pre-netfilter package system that will work fine.
